### ISSUE TITLE
Stampa stringa errata

### ISSUE THREAD

**Issue by trivisonno88** [trivisonno88/Canary-Sunriset#8]
nell'inserimento dei caratteri errati per la data ,il sistema risponde con stringa "dati non presenti nel database" anche se in realtà sono presenti.

**Comment by midivico** [comment]
Controllo sulla data inserita fatto. Aggiorno le pagine luminosita.php, temperatura.php, umidita.php

**Comment by midivico** [comment]
Effettuo il pull repository
