### ISSUE TITLE
Problema_server_rete_LAN

### ISSUE THREAD

**Issue by midivico** [trivisonno88/Canary-Sunriset#9]
Il server non viene visto nella rete locale. Non si riesce ad accedere al server dai dispositivi connessi alla stessa rete.

**Comment by trivisonno88** [comment]
Nel file httpd.config del wamp server é stato sostituito al comando listen l'indirizzo ip 127.0.0.1 con quello della macchina su cui gira. Adessa comunica correttamente

**Comment by midivico** [comment]
Perfetto, ora possiamo settare nel router un indirizzo ip statico sulla macchina dove è istallato il server. In questo modo non dobbiamo cambiare ogni volta l'indirizzo su cui è in ascolto il server nel file https.config.
